#!/bin/sh
csv=$1
matlab -nodesktop -nosplash <<EOF
clear;
addpath(genpath('breach/'));
addpath(genpath('src/test/simulink/'));
InitBreach;


mdl = 'Autotrans_shift_speed_100';
Br = BreachSimulinkSystem(mdl);
Br.Sys.tspan =0:.01:30;
input_gen.type = 'UniStep';
input_gen.cp = 5;
Br.SetInputGen(input_gen);
for cpi = 0:input_gen.cp -1
	throttle_sig = strcat('throttle_u',num2str(cpi));
	Br.SetParamRanges({throttle_sig},[0.0 100.0]);
	brake_sig = strcat('brake_u',num2str(cpi));
	Br.SetParamRanges({brake_sig},[0.0 325.0]);
end
spec = 'alw_[0,30]((gear[t]==4) => (speed[t]>3500))';
phi = STL_Formula('phi',spec);
trials = 30;
filename = 'Autotrans_shift_speed_100_breach_AT7_5_cmaes';
algorithm = 'Breach';
falsified = [];
time = [];
obj_best = [];
num_sim = [];
for n = 1:trials
	falsif_pb = FalsificationProblem(Br,phi);
	falsif_pb.max_time = 600;
	falsif_pb.setup_solver('cmaes');
	falsif_pb.solve();
	if falsif_pb.obj_best < 0
		falsified = [falsified;1];
	else
		falsified = [falsified;0];
	end
	num_sim = [num_sim;falsif_pb.nb_obj_eval];
	time = [time;falsif_pb.time_spent];
	obj_best = [obj_best;falsif_pb.obj_best];
end
spec = {spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec};
filename = {filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename};
result = table(filename, spec, falsified, time,  obj_best, num_sim);
writetable(result,'$csv','Delimiter',';');
quit
EOF

