#!/bin/sh
csv=$1
matlab -nodesktop -nosplash <<EOF
clear;
addpath(genpath('breach/'));
addpath(genpath('src/test/simulink/'));
InitBreach;

fuel_inj_tol=1.0;
MAF_sensor_tol=1.0;
AF_sensor_tol=1.0;
pump_tol=1;
kappa_tol=1;
tau_ww_tol=1;
fault_time=50;
kp=0.04;
ki=0.14;
mdl = 'fuel_control_mu_100';
Br = BreachSimulinkSystem(mdl);
Br.Sys.tspan =0:.01:50;
input_gen.type = 'UniStep';
input_gen.cp = 5;
Br.SetInputGen(input_gen);
for cpi = 0:input_gen.cp -1
	Engine_Speed_sig = strcat('Engine_Speed_u',num2str(cpi));
	Br.SetParamRanges({Engine_Speed_sig},[900.0 1100.0]);
	Pedal_Angle_sig = strcat('Pedal_Angle_u',num2str(cpi));
	Br.SetParamRanges({Pedal_Angle_sig},[8.8 70.0]);
end
spec = '(ev_[0,50](Pedal_Angle[t] > 40))=>(alw_[11,50](mu[t] < 22.5))';
phi = STL_Formula('phi',spec);
trials = 30;
filename = 'fuel_control_mu_100_breach_AFC2_5_cmaes';
algorithm = 'Breach';
falsified = [];
time = [];
obj_best = [];
num_sim = [];
for n = 1:trials
	falsif_pb = FalsificationProblem(Br,phi);
	falsif_pb.max_time = 600;
	falsif_pb.setup_solver('cmaes');
	falsif_pb.solve();
	if falsif_pb.obj_best < 0
		falsified = [falsified;1];
	else
		falsified = [falsified;0];
	end
	num_sim = [num_sim;falsif_pb.nb_obj_eval];
	time = [time;falsif_pb.time_spent];
	obj_best = [obj_best;falsif_pb.obj_best];
end
spec = {spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec;spec};
filename = {filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename;filename};
result = table(filename, spec, falsified, time,  obj_best, num_sim);
writetable(result,'$csv','Delimiter',';');
quit
EOF

